# Source - https://stackoverflow.com/a/50610630
# Posted by hoefling, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-09, License - CC BY-SA 4.0

[pytest]
pythonpath = .
